/// Flutter icons BottomIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomIcon
///      fonts:
///       - asset: fonts/BottomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomIcon {
  BottomIcon._();

  static const _kFontFam = 'BottomIcon';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData room = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visitor = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
